#pragma once
#include <SDL.h>
#include <stdio.h>
#include <SDL_image.h>
#include <string>
#include <vector>
#include <iostream>
#include <sstream>
#include <math.h>
#include <SDL_ttf.h>
#include "tinyxml2.h"